coverage:
  status:
    project:
      default: on
      # Minimum coverage that our project must have
      minimum:
        target: 50%
      # Decrement threshold for code coverage when submitting a PR
      decrement:
        target: auto
        threshold: 0.5%
        if_not_found: success
      # We can set specific targets for our modules
      core:
        target: 50%
    patch:
      default: off
      # Coverage % a PR must have in order to pass
      pr_coverage:
        target: 60% 
